# Generated by Django 4.2.4 on 2023-09-02 00:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('opcionais', '0001_initial'),
        ('motor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carroceria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nome', models.CharField(max_length=70)),
                ('Versao', models.CharField(max_length=70)),
                ('Ano', models.IntegerField()),
                ('Motor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='motor.motor')),
                ('Opcionais', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='opcionais.opcionais')),
            ],
        ),
    ]
