# Generated by Django 4.2.4 on 2023-09-02 02:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carroceria', '0002_remove_carroceria_opcionais_carroceria_opcionais'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carroceria',
            old_name='opcionais',
            new_name='Opcionais',
        ),
    ]
